### PR TITLE
[MPLUGIN-447] Update to Maven Parent POM 39

### PR DESCRIPTION
**Pull request by kwin**
This requires a dedicated follow-up commit according to https://lists.apache.org/thread/14n13z4sh3twy5qgp5f487f1z0s5pc4s

### CODE REVIEW

**Comment by slawekjaranowski** [comment]
Please fix checkstyle configuration like in: https://github.com/apache/maven-dependency-plugin/pull/266
and check site reports

**Comment by kwin** [comment]
> Please fix checkstyle configuration like in: [apache/maven-dependency-plugin#266](https://github.com/apache/maven-dependency-plugin/pull/266) and check site reports

Done now.

**Review by gnodet — APPROVED** [review]

**Review by slawekjaranowski — APPROVED** [review]

**Comment by elharo** [comment]
Why does upgrading the parent POM reformat pretty much every file? That seems like a very different thing.

**Comment by kwin** [comment]
> Why does upgrading the parent POM reformat pretty much every file? That seems like a very different thing.

That is because the code format conventions have changed. There was a mailing list discussion around that.

**Comment by slawekjaranowski** [comment]
@kwin look for duplicate License headers

can help:

```
git grep -c "Licensed to the Apache Software Foundation" | grep -v ":1"
```

**Comment by kwin** [comment]
> @kwin look for duplicate License headers
> 
> can help:
> 
> ```
> git grep -c "Licensed to the Apache Software Foundation" | grep -v ":1"
> ```

Thanks for the hint. Is there a configuration in spotless to remove those duplicates or do you have a script for that available as well? Seems that almost all files have duplicate license headers after the automated formatting…

**Comment by slawekjaranowski** [comment]
> > @kwin look for duplicate License headers
> > can help:
> > ```
> > git grep -c "Licensed to the Apache Software Foundation" | grep -v ":1"
> > ```
> 
> Thanks for the hint. Is there a configuration in spotless to remove those duplicates or do you have a script for that available as well? Seems that almost all files have duplicate license headers after the automated formatting…

In IDE I copy old header and use options replace all.

**Pull request merged**
