### PR TITLE
[MPLUGIN-492] Documentation for plugins in general: Goals comprises m…

### PR DESCRIPTION
**Pull request by michael-o**
…ore than that

This closes #252

### CODE REVIEW

**Comment by michael-o** [comment]
@Reissner have a look.

**Review by slawekjaranowski — APPROVED** [review]
I hope that translations are ok 😄

**Comment by michael-o** [comment]
> I hope that translations are ok 😄

It is, hand-crafted, native level.

**Comment by jira-importer** [comment]
Resolve #810

**Pull request merged**
