### PR TITLE
[MPLUGIN-473] Only check direct dependencies for provided scope

### PR DESCRIPTION
**Pull request by gnodet**
This relaxes the check a bit and provides support for plexus-xml 4.0.0
JIRA issue: https://issues.apache.org/jira/browse/MPLUGIN-473

### CODE REVIEW

**Comment by gnodet** [comment]
This should provide a fix for https://github.com/codehaus-plexus/plexus-utils/issues/256 and https://github.com/codehaus-plexus/plexus-xml/issues/16

**Comment by slawekjaranowski** [comment]
I'm not sure if it is good way to resolve problems with plexus-utils and maven-xml* artifacts. 
Currently we have a validators in Maven core which check also transitive dependencies. 
So here verifications should be even more strict than in Maven core.
Maybe we can exclude maven-xml* artifacts?

@cstamas what do you think?

**Comment by gnodet** [comment]
> I'm not sure if it is good way to resolve problems with plexus-utils and maven-xml* artifacts. Currently we have a validators in Maven core which check also transitive dependencies. So here verifications should be even more strict than in Maven core. Maybe we can exclude maven-xml* artifacts?
> 
> @cstamas what do you think?

That was a wrong idea.  The plexus-xml is actually provided by maven 3 and 4 (at least the classes), so in most cases, the `plexus-xml` dependency itself should be flagged as provided (contrary to the `plexus-utils` one).

**Comment by jira-importer** [comment]
Resolve #784

**Pull request closed without merging**
