### PR TITLE
[MPLUGIN-529] Add new report goal 'report-no-fork' which will not invoke process-classes

### PR DESCRIPTION
**Pull request by mattnelson**
Forward patch of #310 to 4.x

### CODE REVIEW

**Comment by mattnelson** [comment]
@michael-o The build failure appeared to be because the IT used on 3.x was using javadoc tags instead of annotations. Would you like to have the 3.x test be updated as well?

**Comment by michael-o** [comment]
> @michael-o The build failure appeared to be because the IT used on 3.x was using javadoc tags instead of annotations. Would you like to have the 3.x test be updated as well?

Yes, please.

**Comment by michael-o** [comment]
@mattnelson I would be worthwhile to backport he annotations patch to the 3.x branch as well.

**Review by michael-o — APPROVED** [review]

**Comment by michael-o** [comment]
I have discovered a few more cleanups required prior this can be merged. Please stay put.

**Comment by jira-importer** [comment]
Resolve #847

**Pull request merged**
