### PR TITLE
[MPLUGIN-419] Fix documentation for maven-plugin-report-plugin

### PR DESCRIPTION
**Pull request by slawekjaranowski**

### CODE REVIEW

**Review by kwin — CHANGES_REQUESTED** [review]
I would suggest to move the examples links to the parent at https://github.com/apache/maven-plugin-tools/blob/master/src/site/site.xml so it is available in all modules (even in non-Maven plugin ones). WDYT?

**Comment by slawekjaranowski** [comment]
> I would suggest to move the examples links to the parent at https://github.com/apache/maven-plugin-tools/blob/master/src/site/site.xml so it is available in all modules (even in non-Maven plugin ones). WDYT?

I can try in such way.

@kwin can you look at build on jenkins ... 
Maven site build is broken with error:
```
javadoc: error - An internal exception has occurred. 
	(java.lang.NullPointerException)
Please file a bug against the javadoc tool via the Java bug reporting page
(http://bugreport.java.com/) after checking the Bug Database (http://bugs.java.com/)
for duplicates. Include error messages and the following diagnostic in your report. Thank you.
java.lang.NullPointerException
	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.util.Utils.getFileObject(Utils.java:834)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.SourceToHTMLConverter.convertClass(SourceToHTMLConverter.java:176)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.SourceToHTMLConverter.generate(SourceToHTMLConverter.java:136)
	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.SourceToHTMLConverter.convertRoot(SourceToHTMLConverter.java:117)
```
Very strange ....
from build: https://ci-maven.apache.org/job/Maven/job/maven-box/job/maven-plugin-tools/job/master/60/

on GitHub the same pass

**Comment by kwin** [comment]
The NPE in javadoc started with commit https://github.com/apache/maven-plugin-tools/commit/31d088e969f9863370256db3ab0ba71b2c75534f according to https://ci-maven.apache.org/job/Maven/job/maven-box/job/maven-plugin-tools/job/master/. No idea about it as I cannot reproduce locally.

**Comment by slawekjaranowski** [comment]
NEP in javadocs fixed in #157

**Review by gnodet — APPROVED** [review]

**Comment by slawekjaranowski** [comment]
Connected with issue https://issues.apache.org/jira/browse/MPLUGIN-430

**Pull request merged**
