### PR TITLE
Add missing @Override and make methods static

### PR DESCRIPTION
**Pull request by gaul**
Found via error-prone.

### CODE REVIEW

**Comment by gaul** [comment]
Does anything block merging this?

**Comment by rfscholte** [comment]
> Does anything block merging this?

Time and resources

**Comment by Tibor17** [comment]
LGTM

**Comment by Tibor17** [comment]
@rfscholte 
Not sure how about you, but I started the build in few seconds and seen changes (static private method and one Override annotation).

**Comment by Tibor17** [comment]
Build passed, merging...

**Comment by Tibor17** [comment]
@gaul Thx for contributing. You are welcome with new pullrequests.

**Pull request merged**
