### PR TITLE
[MPLUGIN-384] restore compatibility with Maven 3 ecosystem

### PR DESCRIPTION
**Pull request by hboutemy**
https://issues.apache.org/jira/browse/MPLUGIN-384

### CODE REVIEW

**Review by kwin — COMMENTED** [review]
IIUC then two dependencies would expose the same fqcn (compat and m-p-p). Wouldn't that potentially cause trouble (ClassCastException) I think at least a hint in the javadoc is in order.

**Comment by hboutemy** [comment]
I think that Maven class loading won't load the class from the plugin: it is taken from Maven core classloader (that contains compat), see https://maven.apache.org/guides/mini/guide-maven-classloading.html
but you're right that it deserves testing in real life to check that I'm not wrong (IIRC, I already saw such a class copy in another case, but I don't remember where)...

**Comment by slawekjaranowski** [comment]
I checked with real environment, metadata to oss was deployed correctly.

**Review by slawekjaranowski — APPROVED** [review]

**Comment by hboutemy** [comment]
thank you Slawomir

**Comment by jira-importer** [comment]
Resolve #688

**Pull request merged**
