### PR TITLE
[MPLUGIN-394] use XmlStreamReader to detect encoding instead of platform

### PR DESCRIPTION
**Pull request by hboutemy**

### CODE REVIEW

**Comment by slawekjaranowski** [comment]
Is it possible to prepare a test which can confirm that works as expected?

**Comment by slawekjaranowski** [comment]
please also rebase with current master base code.

**Comment by slawekjaranowski** [comment]
#73 - next with tests 😄

**Comment by hboutemy** [comment]
interesting bits with XmlStreamReader to be merged to #73

**Pull request closed without merging**
