### PR TITLE
[MPLUGIN-386] Lower the tone and limit the scope check to maven-plugin-api only

### PR DESCRIPTION
**Pull request by cstamas**
The warning was too chatty, a bit pushy, and also it
triggered on too broad condition (all of org.apache.maven groupIds).

This change makes following modifications:
* only maven-plugin-api is checked for (so JXR, Archiver will not trigger it)
* message is really one liner about best practice (if anyone curious, go after it anyway)

---

https://issues.apache.org/jira/browse/MPLUGIN-386

### CODE REVIEW

**Review by slachiewicz — APPROVED** [review]
Yes yes, also saw that earlier

**Review by michael-o — COMMENTED** [review]
I don't understand this change. Why only the plugin API? Ignoring Archiver and JXR for now.

**Review by rmannibucau — APPROVED** [review]
approving since we can't do really better for now but will need to be revisited anyway since both (only this or all maven*) strategies are wrong and we need to cover the actual stable maven API

**Comment by cstamas** [comment]
Superseded by https://github.com/apache/maven-plugin-tools/pull/58

**Comment by jira-importer** [comment]
Resolve #686

**Pull request closed without merging**
